{% set name = "apache-airflow-providers-elasticsearch" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-elasticsearch-{{ version }}.tar.gz
  sha256: 0ab399b5f06c8d80731c0b720ddfe8fdbdde1eb6ccb059d0ce46425836075e67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - elasticsearch >7
    - elasticsearch-dbapi
    - elasticsearch-dsl >=5.0.0

test:
  imports:
    - airflow.providers.elasticsearch
    - airflow.providers.elasticsearch.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-elasticsearch package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_file:
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
