{% set name = "apache-airflow-providers-elasticsearch" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-elasticsearch-{{ version }}.tar.gz
  sha256: 1dbdec005ddc48b26a4804bfcce38b26e9ca0d13a5ad9a760e93b78f23effbd2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - elasticsearch >7
    - elasticsearch-dbapi
    - elasticsearch-dsl >=5.0.0

test:
  imports:
    - airflow.providers.elasticsearch
    - airflow.providers.elasticsearch.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Elasticsearch for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
