{% set name = "apache-airflow-providers-elasticsearch" %}
{% set version = "5.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_elasticsearch-{{ version }}.tar.gz
  sha256: 49ccee5333d62dbe236f83dce256e5382fdd1b97a9dff321931a6e456eb528d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    - elasticsearch >=8.10,<9

test:
  imports:
    - airflow.providers.elasticsearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-elasticsearch for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/elasticsearch/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
