{% set name = "apache-airflow-providers-elasticsearch" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-elasticsearch-{{ version }}.tar.gz
  sha256: 4a17a8cec4c86929c3f723bad3d0b9d5f542cb3c9e29a310484c123cd46d50d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - apache-airflow >=2.0.0
    - elasticsearch >7,<7.6.0
    - elasticsearch-dbapi 0.1.0
    - elasticsearch-dsl >=5.0.0

test:
  imports:
    - airflow.providers.elasticsearch
    - airflow.providers.elasticsearch.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Elasticsearch for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
